// Portable two-scene original fixture. Tests new engine behavior, not DM1 content.
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const source=path.resolve(process.argv[2]||path.join(__dirname,'../skills/dragon-masters-interactive-book/assets/starter'));
const root=fs.mkdtempSync(path.join(os.tmpdir(),'book contract '));fs.cpSync(source,root,{recursive:true});
const original=JSON.parse(fs.readFileSync(path.join(root,'story.json'))),data=structuredClone(original);
data.id='contract-fixture';data.title={en:'The Brass Bird',zh:'黄铜鸟'};data.description={en:'An original test story.',zh:'原创测试故事。'};data.ending={en:'The bird returns to its shelf.',zh:'小鸟回到架子。'};
const first=structuredClone(data.scenes[0]),last=structuredClone(data.scenes[1]);first.id='entry';first.chapterId='ch01';first.action={type:'advance',label:{en:'Enter workshop',zh:'进入'}};first.quiz=null;first.afterImage='art/lit.svg';
last.id='flight';last.chapterId='ch01';last.action={type:'track',sprite:'art/gear.svg',width:12,path:'M200 500 C400 150 600 850 800 500',label:{en:'Guide the bird',zh:'带小鸟飞行'}};last.retell={prompt:{en:'Order the events.',zh:'排列事件。'},items:[{id:'a',text:{en:'enter',zh:'进入'}},{id:'b',text:{en:'guide',zh:'引导'}}],order:['a','b']};data.scenes=[first,last];
const sync=()=>{fs.writeFileSync(path.join(root,'story.json'),JSON.stringify(data));fs.writeFileSync(path.join(root,'story.js'),'window.BOOK = '+JSON.stringify(data)+';');};sync();
(async()=>{const checks=[],errors=[],browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||undefined,args:['--allow-file-access-from-files']});
const check=(name,pass)=>{checks.push({name,pass:!!pass});if(!pass)throw Error(name);};
try{for(const reduced of [false,true]){const page=await browser.newPage({viewport:reduced?{width:1440,height:900}:{width:1280,height:800},reducedMotion:reduced?'reduce':'no-preference'});page.on('pageerror',e=>errors.push(e.message));
await page.goto(pathToFileURL(path.join(root,'index.html')).href);check('source title on cover',await page.locator('#coverTitle').textContent()==='The Brass Bird');check('no demo conclusion on cover',!(await page.locator('#cover').textContent()).includes('Fog'));
await page.locator('#open').click();await page.getByRole('button',{name:'Enter workshop',exact:true}).click();await page.getByRole('button',{name:'Continue →',exact:true}).click();check('intermediate scene has no quiz',await page.locator('.quiz').count()===0);await page.getByRole('button',{name:'Next scene →',exact:true}).click();await page.waitForSelector('#layers button');
const track=page.locator('#layers button');await track.focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('Escape');check('track Escape cancels',await track.getAttribute('data-progress')==='0');
for(let i=0;i<40;i++)await page.keyboard.press('ArrowRight');await page.waitForTimeout(80);check('track endpoint waits for release/Enter',await page.evaluate(()=>!state.steps.flight));await page.keyboard.press('Enter');await page.getByRole('button',{name:'Story check →',exact:true}).waitFor();
await page.locator('#readLabel').click();check('reading opens before question',await page.locator('#readingBox').getAttribute('open')!==null);await page.getByRole('button',{name:'Story check →',exact:true}).click();check('quiz hides expanded reading',await page.locator('#readingBox').isHidden());check('quiz hides journal',await page.locator('#journal').isHidden());check('quiz clears caption',(await page.locator('#caption').textContent())==='');
const wrong=last.quiz.options.find(o=>o.id!==last.quiz.answer).id;await page.locator(`[data-option="${wrong}"]`).click();check('wrong answer cannot finish',await page.evaluate(()=>state.steps.flight===2));await page.getByRole('button',{name:'Review evidence',exact:true}).click();check('review restores reading',await page.locator('#readingBox').isVisible());await page.getByRole('button',{name:'Story check →',exact:true}).click();await page.locator(`[data-option="${last.quiz.answer}"]`).click();
check('completed track retains sprite',await page.locator('#layers button[disabled]').count()===1);await page.getByRole('button',{name:'Replay flight',exact:true}).click();await page.waitForSelector('#layers button:not([disabled])');await page.locator('#layers button').focus();await page.keyboard.press('ArrowRight');check('replay preserves completed story',await page.evaluate(()=>state.steps.flight===3));await page.getByRole('button',{name:'Return to story',exact:true}).click();await page.getByRole('button',{name:'Close the book',exact:true}).waitFor();
check('custom ending shown',(await page.locator('#panel').textContent()).includes('The bird returns to its shelf.'));await page.locator('.retell summary').click();check('retell begins shuffled',(await page.locator('.retell li span').allTextContents()).join(',')==='guide,enter');await page.getByRole('button',{name:'Up',exact:true}).nth(1).click();await page.getByRole('button',{name:'Check sequence',exact:true}).click();check('retell can verify sequence',(await page.locator('.retell').textContent()).includes('Sequence ready'));
await page.locator('#language').click();await page.reload();await page.locator('#open').click();await page.waitForFunction(()=>!document.querySelector('.loading'));check('progress language and retell survive reload',await page.evaluate(()=>state.steps.flight===3&&state.language==='both'&&state.retells.flight.join(',')==='a,b'));
if(process.env.SCREENSHOT_DIR){fs.mkdirSync(process.env.SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,reduced?'production-reduced.png':'production-normal.png')});}
await page.getByRole('button',{name:/Close the book/}).click();check('retell does not block closing',await page.locator('#cover').isVisible());await page.close();}
// Missing sprite must block controls, then Retry must recover without losing state.
data.scenes[0].action={type:'track',sprite:'art/missing.svg',path:'M100 500 L900 500',label:{en:'Track missing sprite',zh:'飞行'}};sync();const page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(root,'index.html')).href);await page.locator('#open').click();await page.getByRole('button',{name:'Retry',exact:true}).waitFor();check('missing sprite blocks action',await page.locator('#layers button').count()===0);check('failed asset does not complete',await page.evaluate(()=>!state.steps.entry));fs.copyFileSync(path.join(root,'art/gear.svg'),path.join(root,'art/missing.svg'));await page.getByRole('button',{name:'Retry',exact:true}).click();await page.waitForSelector('#layers button');check('sprite retry recovers',await page.locator('#layers button').count()===1);await page.close();
// Long props preserve size and aspect across the drag and result states.
data.scenes[0].action={type:'drag',sprite:'art/gear.svg',from:[20,40],to:[70,50],radius:8,width:18,aspectRatio:2,label:{en:'Carry the prop',zh:'移动道具'}};delete data.scenes[0].afterImage;sync();const dragpage=await browser.newPage();dragpage.on('pageerror',e=>errors.push(e.message));await dragpage.goto(pathToFileURL(path.join(root,'index.html')).href);await dragpage.locator('#open').click();const moving=dragpage.locator('.prop');await moving.waitFor();const start=await moving.boundingBox(),target=await dragpage.locator('.target').boundingBox();check('custom prop aspect ratio applied',Math.abs(start.width/start.height-2)<.01);await dragpage.mouse.move(start.x+start.width/2,start.y+start.height/2);await dragpage.mouse.down();await dragpage.mouse.move(target.x+target.width/2,target.y+target.height/2,{steps:12});await dragpage.mouse.up();await dragpage.locator('.placed').waitFor();const end=await dragpage.locator('.placed').boundingBox();check('placed prop retains dimensions',Math.abs(end.width-start.width)<1&&Math.abs(end.height-start.height)<1);await dragpage.close();

}catch(e){errors.push(String(e));}finally{await browser.close();fs.rmSync(root,{recursive:true,force:true});}
const result={checks,errors,scope:'Original synthetic fixture; not full DM1 adaptation'};if(process.env.OUTPUT_REPORT){fs.mkdirSync(path.dirname(process.env.OUTPUT_REPORT),{recursive:true});fs.writeFileSync(process.env.OUTPUT_REPORT,JSON.stringify(result,null,2));}console.log(JSON.stringify(result,null,2));if(errors.length)process.exitCode=1;})();
